# Generated by Django 5.0.6 on 2024-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emriApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_hours',
            new_name='item_motorri',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_week',
            new_name='item_vitiprodhimit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_karburanti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_lloji',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
