# Generated by Django 5.0.6 on 2024-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emriApp', '0002_rename_item_hours_item_item_motorri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='item/')),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
